### ISSUE TITLE
Ideas for adventures

### ISSUE THREAD

**Issue by gogi** [fantasygame/campaigns#25]
- all members can add ideas but only author and game master can see them
- game master can see all ideas for his campaign

**Comment by jkubacki** [comment]
game master can like an idea (1 point in calculator)
game master can mark an idea as used (another 1 point)

**Comment by jkubacki** [comment]
Another ideas:
Pagination + searching (you can use kaminari)

**Comment by gogi** [comment]
Game master can mark idea as used 492961ef082290d1c10d5b5983e2a0e3d40bd400
and also mark it as interesting b20c1357ce687b5ff8d9d036eca4a0df8efa41de

**Comment by gogi** [comment]
Only author or game master can see ideas 437d300a388c68df16717070068a902efa177ea0

**Comment by gogi** [comment]
Interesting idea add 1 point to calculator and when idea is used, another point will be add to calculator 2519bf33253be5179888388c706c25975b0d0dae

**Comment by gogi** [comment]
Pagination has been added 68f122ca084c7bed6011974c3e7b3a60c6214749

**Comment by gogi** [comment]
Simple search method has been implemented:
848a3bafb3c654ef5bd5a46d61555aca590df6de
975ba6de5cb0777a503bffeca8aeb7308dfb8550

**Comment by gogi** [comment]
Only tests left to do

**Comment by jkubacki** [comment]
Nice! Things to fix/consider:
- love instead of like icon
- user should see that his idea was loved and used
- search box is invisible if there is no collection
- search box styling
- email notification about new idea for game master
- bigger pagination (10)
- ideas can be public - visible for everyone

**Comment by gogi** [comment]
Changes:
- heart instead of thumb 85e1a361d517ced8891fd15a232f9e5cfccf0eb9
- user can see if his idea is liked or not 62e21ab3f5c1b900b77627335a14a35a34c81ccd
- user can see if his idea has been used 1388202784a9a77791ea520f9091dfef403a965b
- search box is always visible a24fb79c3cd485eca738a91534ced8b6d7c43f5c
- bootstrap style in search box e07bceddfcd271c538218080ac58c7d725da188b
- pagination 10 c9171dab9b097458d38403babef9a8879e3ddd36

To do:
- email notification about new idea for game master
- ideas can be public - visible for everyone

**Comment by gogi** [comment]
Ideas can be visible for all members be3a8fed1709c4b728b6785e616151848f79b92c

**Comment by gogi** [comment]
notification for game master about new idea db637dec6c96fcf1e7d35882c6b91f7ca05203c4

**Comment by jkubacki** [comment]
NICE job!

User who adds an idea should have option to make it visible or not. It should be handled by form checkbox, not the toggle button. That way user and gamemaster can edit this value. Idea should be invisible as default as it it now.

**Comment by jkubacki** [comment]
Ok, feature is already user-tested. Comments happened to be must-have.

Ideally there would be no need to make new model for comment. We could make polimorfic association between comment and subject of the comment.

So instead of `belongs_to :post` it would be `belongs_to :subject, polymorphic: true`

@gogi This is kinda advanced and something new for you to tackle. Give it a try.

It's crucial not to loose connection between our comments and posts. There are many of them in database and it could be a real problem. So we must do it gradually.
1. make new polymorphic subject association
2. write rake task that will copy post associations to subject
3. run rake task in development and (IMPORTANT) in heroku production
4. Make sure, that production associations are copied properly
5. Doublecheck
6. Write migration to remove old association

@pabielicki You could make all the other work

Adding comments:
- In idea show there should be comment button (same color and icon as in posts)
- Button should open up form for adding new comment
- Comment text area should be formatted with bootstrap classes like all other forms in the app
- Comment should validate presence of content
- Invalid form (without comment) should rerender form with errored field highlighted red (default behaviour)
- After comment is created it should redirect to idea show
- All idea comments should be displayed in idea show. Similar to post comments
- Owner of comment (and only him) should be able to edit and remove comment. (subtle edit/remove buttons near comment)
- Apply this also to posts comments. They can be modified for now.

Email notifications:
- after every comment game_master and user should be notified
- every other user that left comment in this idea (in public ideas) should also be notified
- user that leaves comment shouldn't be notified
- email should have html and text template. comment content should be sent as well as url to idea

**Comment by jkubacki** [comment]
@pabielicki I've added comments for ideas (didn't migrate posts yet). So you can start your part if you want.

**Comment by jkubacki** [comment]
Ok, I finished @gogi part with making comments polymorphic. Moved posts associations to subject, removed post column and made adjustments everywhere for it to work fine.

Adding posting to ideas should be simple now @pabielicki. Maybe I will handle it tomorrow. IDK yet :P Let me know if you wanna do this.

**Comment by jkubacki** [comment]
Ok, finished all :)
